; generated by lcc-xr18fl $Version: 4.0 - XR18FL - St. Judy's Compiler $ on Sun Apr 07 15:41:36 2013

SP:	equ	2 ;stack pointer
memAddr: equ	14
retAddr: equ	6
retVal:	equ	15
regArg1: equ	12
regArg2: equ	13
	listing off
	include lcc1802ProloFL.inc
	listing on
_main:
	reserve 4
;void main(){
;	i=intfunc();
	Ccall _intfunc
	cpy2 R11,R15 ;LOADI2(reg)*
	st2 R11,'D',(_i),0; ASGNI2(addr,reg)*;
;}
L1:
	release 4
	Cretn

_i:
	db 2 dup (0); zerofill global
	include lcc1802Epilofl.inc
	include IO1802.inc
