#!/bin/sh

# ATMEL OTP - AT27C020@DIP32
# SST NOR FLASH - SST39SF020A
# GLS NOR FLASH - SST27SF020@DIP32

# firmware
echo "Assemble Firmware"
echo ":020000040000FA" > build/output/rom.hex

for f in src/sys src/hal src/intel src/ext
do
  echo $f
  build/asm_hex.rb $f >> build/output/rom.hex
done

build/asm_hex.rb boot >> build/output/rom.hex

echo "Copy Cold Storage"
echo ":020000040001F9" >> build/output/rom.hex
build/repack_hex.rb lib/boot.hex 0 >> build/output/rom.hex
build/repack_hex.rb lib/disk.hex 1 >> build/output/rom.hex
build/repack_hex.rb lib/kernel.hex 2 >> build/output/rom.hex
build/repack_hex.rb lib/monitor.hex 10 >> build/output/rom.hex
build/pack_hex.rb lib/bdir.hex 18 >> build/output/rom.hex

build/bin2hex.rb lib/asm.com 20 >> build/output/rom.hex
build/repack_hex.rb lib/basic.hex 52 >> build/output/rom.hex
build/repack_hex.rb lib/cpm22.hex 88 >> build/output/rom.hex
build/bin2hex.rb lib/ddt.com 116 >> build/output/rom.hex
build/bin2hex.rb lib/dump.com 136 >> build/output/rom.hex
build/bin2hex.rb lib/ed.com 140 >> build/output/rom.hex
build/repack_hex.rb lib/format.hex 168 >> build/output/rom.hex
build/bin2hex.rb lib/load.com 172 >> build/output/rom.hex
build/bin2hex.rb lib/pip.com 180 >> build/output/rom.hex
build/bin2hex.rb lib/stat.com 212 >> build/output/rom.hex
build/bin2hex.rb lib/submit.com 236 >> build/output/rom.hex
build/repack_hex.rb lib/uptime.hex 244 >> build/output/rom.hex
build/repack_hex.rb lib/xfer.hex 248 >> build/output/rom.hex
build/bin2hex.rb lib/xsub.com 252 >> build/output/rom.hex

echo "Building ALU"
build/alu_hex.rb >> build/output/rom.hex

echo "Building Fonts"
build/font_hex.rb >> build/output/rom.hex

echo ":00000001FF" >> build/output/rom.hex

echo "Burn ROM"
minipro -p "SST39SF020A" -w "build/output/rom.hex" -f ihex
