#!/bin/sh

# ATMEL OTP - AT27C020@DIP32
# SST NOR FLASH - SST39SF020A
# GLS NOR FLASH - SST27SF020@DIP32

# firmware
echo "Assemble Firmware"
echo ":020000040000FA" > build/output/rom.hex

for f in src/sys src/hal src/intel src/dev
do
  echo $f
  build/asm_hex.rb $f >> build/output/rom.hex
done

build/asm_hex.rb boot >> build/output/rom.hex

echo "Copy Cold Storage"
cat build/output/cold.hex >> build/output/rom.hex

echo "Building ALU"
build/alu_hex.rb >> build/output/rom.hex

echo "Building Fonts"
build/font_hex.rb >> build/output/rom.hex

echo ":00000001FF" >> build/output/rom.hex

echo "Burn ROM"
minipro -p "SST39SF020A" -w "build/output/rom.hex" -f ihex
