; generated by lcc-xr182b $Version: 4.0 - XR182b $ on Thu Apr 25 16:28:15 2013

SP:	equ	2 ;stack pointer
memAddr: equ	14
retAddr: equ	6
retVal:	equ	15
regArg1: equ	12
regArg2: equ	13
	listing off
	include lcc1802ProloFL.inc
	listing on
L2:
	db 2 dup (0); zerofill global
_memcmp:
	reserve 14
	st2 r12,'O',sp,(16); flag1 
	st2 r13,'O',sp,(18); flag1 
	ldaD R12,L4; reg:acon
	ld2 R11,'D',(L2),0 ;reg:INDIRI2(addr)
	incm R11,1
	st2 R11,'D',(L2),0; ASGNI2(addr,reg)*;
	st2 R11,'O',sp,(-4+16); ASGNI2(addr,reg)*;
	cpy2 R13,R11 ;LOADI2(reg)*
	ld2 R11,'O',sp,(0+16);reg:  INDIRP2(addr)
	st2 r11,'O',sp,(4); arg+f**
	ld2 R11,'O',sp,(2+16);reg:  INDIRP2(addr)
	st2 r11,'O',sp,(6); arg+f**
	ld2 R11,'O',sp,(4+16); reg:INDIRU2(addr)
	st2 r11,'O',sp,(8); arg+f**
	Ccall _printf
;int memcmp(const void *Ptr1, const void *Ptr2, unsigned int Count){
;    return 0;
	ld2z R11
	st2 R11,'O',sp,(-6+16); ASGNI2(addr,reg)*;
	ldaD R12,L6; reg:acon
	ld2 R13,'O',sp,(-4+16) ;reg:INDIRI2(addr)
	ld2 R11,'O',sp,(-6+16) ;reg:INDIRI2(addr)
	st2 r11,'O',sp,(4); arg+f**
	Ccall _printf
	ld2 R15,'O',sp,(-6+16) ;reg:INDIRI2(addr)
L1:
	release 14
	Cretn

L8:
	db 2 dup (0); zerofill global
_main:
	reserve 10
	ldaD R12,L10; reg:acon
	ld2 R11,'D',(L8),0 ;reg:INDIRI2(addr)
	incm R11,1
	st2 R11,'D',(L8),0; ASGNI2(addr,reg)*;
	st2 R11,'O',sp,(-6+12); ASGNI2(addr,reg)*;
	cpy2 R13,R11 ;LOADI2(reg)*
	Ccall _printf
;void main(){
;	pigs=memcmp(0,0,0);
	ldaD R11,0; reg:acon
	cpy2 R12,R11 ;LOADP2(reg)
	cpy2 R13,R11 ;LOADP2(reg)
	ld2z R11
	st2 r11,'O',sp,(4); arg+f**
	Ccall _memcmp
	cpy2 R11,R15 ;LOADI2(reg)*
	st2 R11,'O',sp,(-4+12); ASGNI2(addr,reg)*;
	ldaD R12,L11; reg:acon
	ld2 R13,'O',sp,(-6+12) ;reg:INDIRI2(addr)
	Ccall _printf
;}
L7:
	release 10
	Cretn

L11:
	db 109
	db 97
	db 105
	db 110
	db 35
	db 48
	db 120
	db 37
	db 100
	db 32
	db 114
	db 101
	db 116
	db 117
	db 114
	db 110
	db 101
	db 100
	db 10
	db 0
L10:
	db 109
	db 97
	db 105
	db 110
	db 35
	db 48
	db 120
	db 37
	db 100
	db 40
	db 41
	db 32
	db 99
	db 97
	db 108
	db 108
	db 101
	db 100
	db 10
	db 0
L6:
	db 109
	db 101
	db 109
	db 99
	db 109
	db 112
	db 35
	db 48
	db 120
	db 37
	db 100
	db 32
	db 114
	db 101
	db 116
	db 117
	db 114
	db 110
	db 101
	db 100
	db 32
	db 48
	db 120
	db 37
	db 100
	db 10
	db 0
L4:
	db 109
	db 101
	db 109
	db 99
	db 109
	db 112
	db 35
	db 48
	db 120
	db 37
	db 100
	db 40
	db 80
	db 116
	db 114
	db 49
	db 61
	db 40
	db 99
	db 111
	db 110
	db 115
	db 116
	db 32
	db 118
	db 111
	db 105
	db 100
	db 32
	db 42
	db 41
	db 48
	db 120
	db 37
	db 120
	db 44
	db 80
	db 116
	db 114
	db 50
	db 61
	db 40
	db 99
	db 111
	db 110
	db 115
	db 116
	db 32
	db 118
	db 111
	db 105
	db 100
	db 32
	db 42
	db 41
	db 48
	db 120
	db 37
	db 120
	db 44
	db 67
	db 111
	db 117
	db 110
	db 116
	db 61
	db 48
	db 120
	db 37
	db 120
	db 41
	db 32
	db 99
	db 97
	db 108
	db 108
	db 101
	db 100
	db 10
	db 0
	include lcc1802Epilofl.inc
	include IO1802.inc
