; generated by lcc-xr18fl $Version: 4.0 - XR18FL - St. Judy's Compiler $ on Fri May 17 09:30:48 2013

SP:	equ	2 ;stack pointer
memAddr: equ	14
retAddr: equ	6
retVal:	equ	15
regArg1: equ	12
regArg2: equ	13
	listing off
	include lcc1802ProloFL.inc
	listing on
	align 4
_fourtytwo:
	dd 0x42280000
	align 4
_minusfourtytwo:
	dd 0xc2280000
	align 4
_fourty:
	dd 0x42200000
	align 4
_minusfourty:
	dd 0xc2200000
	align 4
_one:
	dd 0x3f800000
	align 4
_minusone:
	dd 0xbf800000
	align 4
_pigs:
	dd 0x40e00000
_intfun:
;int intfun(){
;	return 7;
	ldaD R15,7; reg:acon
L1:
	Cretn

_main:
	reserve 10
;{
;	i=intfun()*7;
	Ccall _intfun
	cpy2 R11,R15 ;LOADI2(reg)*
	ldaD R12,7; reg:acon
	cpy2 R13,R11 ;LOADI2(reg)*
	Ccall _mulu2; was mulI2 R15,R12,R13
	cpy2 R11,R15 ;LOADI2(reg)*
	st2 R11,'O',sp,(-4+12); ASGNI2(addr,reg)*;
;	if (i==j) k=0;
	ld2 R11,'O',sp,(-4+12) ;reg:INDIRI2(addr)
	ld2 R10,'O',sp,(-6+12) ;reg:INDIRI2(addr)
	jneU2 r11,r10,L3; NE
	ld2z R11
	st2 R11,'O',sp,(-8+12); ASGNI2(addr,reg)*;
L3:
;}
L2:
	release 10
	Cretn

	include lcc1802Epilofl.inc
	include IO1802.inc
