; generated by lcc-xr182b $Version: 4.0 - XR182b $ on Thu Apr 25 10:18:29 2013

SP:	equ	2 ;stack pointer
memAddr: equ	14
retAddr: equ	6
retVal:	equ	15
regArg1: equ	12
regArg2: equ	13
	listing off
	include lcc1802ProloFL.inc
	listing on
_fill_checksum:
	reserve 6; save room for local variables
	pushr r0
	pushr r1
	pushr r14
	reserve 0; save room for outgoing arguments
; void fill_checksum() {
	lbr L3
L2:
;  while(2 >1) {
;    sum += (unsigned int) (((unsigned long)*ptr<<8)|*(ptr+1));
	ld1 R11,'O',R14,0
	zExt R11 ;CVUI2: widen unsigned char to signed int (zero extend)
	cpy2 RL10,R11
	sext4 RL10; CVIU4
	shl4I RL10,8; LSHU4(reg,con)
	ld1 R9,'O',R14,(1)
	zExt R9 ;CVUI2: widen unsigned char to signed int (zero extend)
	cpy2 RL8,R9
	sext4 RL8; CVIU4
	alu4 RL10,RL10,RL8,or,or
	cpy2 R11,RL10 ;LOADU2(reg)*
	cpy2 RL10,R11
	zext4 RL10; CVUI4 jan 16
	alu4 RL0,RL0,RL10,add,adc
;  }
L3:
;  while(2 >1) {
	lbr L2
	lbr L6
L5:
;  while(2 >1) {
;    sum2 += *(unsigned int*)ptr;
	ld4 RL10,'O',sp,(-8+14);reg:  INDIRI4(addr)
	ld2 RL8,'O',R14,0
	zext4 RL8 ;CVUI4: widen unsigned int to signed long (zero extend)
	alu4 RL10,RL10,RL8,add,adc
	st4 RL10,'O',sp,(-8+14)
;  }
L6:
;  while(2 >1) {
	lbr L5
;}
L1:
	release 0; release room for outgoing arguments
	popr r14
	popr r1
	popr r0
	release 6; release room for local variables 
	Cretn

	include lcc1802Epilofl.inc
	include IO1802.inc
